#pragma once
#include "ast/expressions/assignment.hpp"
#include "ast/expressions/binary.hpp"
#include "ast/expressions/compound.hpp"
#include "ast/expressions/conditional.hpp"
#include "ast/expressions/constant.hpp"
#include "ast/expressions/function_call.hpp"
#include "ast/expressions/unary.hpp"
#include "ast/expressions/var.hpp"